# -*- coding: utf-8 -*-
"""Genera fuentes.csv del Informe 01 desde la curaduría de los cinco documentos
de investigación profunda versionados en sources/investigacion-profunda/."""
import csv, io, os

CONF = {  # jerarquía de fuentes del kit canónico §14 → confianza documental
 'politica':85,'base-oficial':80,'curricular':75,'programa-postgrado':75,
 'repositorio':70,'pagina-institucional':70,'proyecto-financiado':70,
 'resultado-institucional':60,'noticia-institucional':50,'prensa-externa':35,
}
ND='FECHA_NO_DECLARADA'
R=[]
def s(sid,uid,title,pub,typ,url,pdate,prec,dstat,wf,by,notes=''):
    R.append(dict(source_id=sid,university_id=uid,title=title,publisher=pub,source_type=typ,
        url=url,archived_url='',published_date=pdate,date_precision=prec,accessed_date='2026-09-01',
        document_status=dstat,confidence=CONF[typ],workflow_status=wf,created_by=by,verified_by='',notes=notes))

# ── Universo nacional (no atribuible a una institución de la cohorte) ──
s('src-nacional-001','','Sistema de Acceso a la Educación Superior · buscador de oferta académica 2026','Ministerio de Educación de Chile','base-oficial','https://acceso.mineduc.cl',ND,ND,'vigente','FUENTE_ABIERTA','intento-3a','Ruta de contraste para construir el universo nacional. No es evidencia sobre ninguna institución.')
s('src-nacional-002','','INDICES · Bases de datos de oferta académica de pregrado 2026','Consejo Nacional de Educación','base-oficial','https://cned.cl/institucional/bases-de-datos','2026-01-08','dia','inaccesible','PROPUESTO','intento-3a','Devuelve 403 a petición automatizada; el sitio es consultable desde navegador. Corte declarado de la base: 08-01-2026.')

# ── Pontificia Universidad Católica de Chile ──
s('src-puc-chile-001','puc-chile','Programa de Derecho, Ciencia y Tecnología UC','Facultad de Derecho UC','pagina-institucional','https://derechocienciaytecnologia.uc.cl',ND,ND,'vigente','FUENTE_ABIERTA','intento-2a','Estructura matriz; mantiene diplomado y curso en Derecho e IA junto a otras líneas tecnológicas.')
s('src-puc-chile-002','puc-chile','Graduación de la generación 2024 de los diplomados del Programa de Derecho, Ciencia y Tecnología UC','Programa de Derecho, Ciencia y Tecnología UC','noticia-institucional','https://derechocienciaytecnologia.uc.cl/2025/01/08/graduacion-de-la-generacion-2024-de-los-diplomados-del-programa-de-derecho-ciencia-y-tecnologia-uc','2025-01-08','dia','vigente','FUENTE_ABIERTA','intento-2a','Acredita ejecución efectiva de la cohorte 2024, no sólo su oferta.')
s('src-puc-chile-003','puc-chile','Graduación de la generación 2025 de los diplomados del Programa de Derecho, Ciencia y Tecnología UC','Programa de Derecho, Ciencia y Tecnología UC','noticia-institucional','https://derechocienciaytecnologia.uc.cl/2026/01/16/graduacion-de-la-generacion-2025-de-los-diplomados-del-programa-de-derecho-ciencia-y-tecnologia-uc','2026-01-16','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-3b','Junto con src-puc-chile-002 forma serie temporal de dos cohortes.')
s('src-puc-chile-004','puc-chile','Derecho UC formaliza la creación del primer Departamento de Derecho y Tecnología en Chile','Facultad de Derecho UC','noticia-institucional','https://derecho.uc.cl/derecho-uc-formaliza-la-creacion-del-primer-departamento-de-derecho-y-tecnologia-en-chile','2025-12-31','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-3a; intento-3b','Anuncio de creación. El acto formal —resolución u organigrama constitutivo— no se ha localizado (L-6).')
s('src-puc-chile-005','puc-chile','Estructura orgánica · Derecho UC Transparente','Facultad de Derecho UC','pagina-institucional','https://derecho.uc.cl/facultad/derecho-uc-transparente/estructura-organica',ND,ND,'vigente','FUENTE_ABIERTA','intento-3a','Lista el Departamento de Derecho y Tecnología como unidad formal. Es el respaldo orgánico de src-puc-chile-004.')
s('src-puc-chile-006','puc-chile','Derecho UC inaugura año académico 2026 con foco en excelencia, innovación y proyección internacional','Facultad de Derecho UC','noticia-institucional','https://derecho.uc.cl/derecho-uc-inaugura-ano-academico-2026-con-foco-en-excelencia-innovacion-y-proyeccion-internacional','2026-05-14','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-3a','Declara la oficialización en el formulario de condiciones y evaluaciones de la opción docente de integrar IA. Prueba el mecanismo, no su adopción por curso.')
s('src-puc-chile-007','puc-chile','Expertos extranjeros y académicos de Derecho UC analizaron la ética en la inteligencia artificial','Facultad de Derecho UC','noticia-institucional','https://derecho.uc.cl/expertos-extranjeros-y-academicos-de-derecho-uc-analizaron-la-etica-en-la-inteligencia-artificial','2026-04-10','dia','vigente','FUENTE_ABIERTA','intento-2b','Identifica a Raúl Madrid como director del Departamento de Derecho y Tecnología.')
s('src-puc-chile-008','puc-chile','Facultad de Derecho UC establece guía ética para uso de inteligencia artificial generativa','Facultad de Derecho UC','politica','https://derecho.uc.cl/facultad-de-derecho-uc-establece-guia-etica-para-uso-de-inteligencia-artificial-generativa','2026-08-21','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-2b; intento-3a; intento-3b','Gobernanza específica de Facultad, no universitaria. Localizada por dos rondas independientes.')
s('src-puc-chile-009','puc-chile','Matías Aránguiz asume como nuevo director del Programa de Derecho, Ciencia y Tecnología','Facultad de Derecho UC','noticia-institucional','https://derecho.uc.cl/matias-aranguiz-asume-como-nuevo-director-del-programa-de-derecho-ciencia-y-tecnologia','2026-01-13','dia','vigente','PROPUESTO','intento-3a','El documento fuente declara que la apertura del original sufrió timeout: no se abrió.')
s('src-puc-chile-010','puc-chile','Seminario analiza el impacto jurídico de la inteligencia artificial en Chile, México y EE. UU.','Programa de Derecho, Ciencia y Tecnología UC','noticia-institucional','https://derechocienciaytecnologia.uc.cl/2025/04/03/seminario-analiza-el-impacto-juridico-de-la-inteligencia-artificial-en-chile-mexico-y-ee-uu','2025-04-03','dia','vigente','FUENTE_ABIERTA','intento-2a','Vinculación con el medio, específica en IA.')
s('src-puc-chile-011','puc-chile','Diplomado en Derecho e Inteligencia Artificial · Educación Continua UC','Educación Continua UC','programa-postgrado','https://educacioncontinua.uc.cl/programas/diplomado-en-derecho-e-inteligencia-artificial',ND,ND,'vigente','FUENTE_ABIERTA','intento-3a','Cohorte en ejecución entre el 04-08-2026 y el 10-12-2026, 180 horas, Facultad de Derecho como unidad responsable.')
s('src-puc-chile-012','puc-chile','AyudantIA UC','Pontificia Universidad Católica de Chile','pagina-institucional','https://docencia.ia.uc.cl/ayudantia',ND,ND,'vigente','FUENTE_ABIERTA','intento-2a','Infraestructura central de la universidad. La fuente no identifica a la Facultad de Derecho ni cursos jurídicos: se atribuye a la universidad, no a la Facultad.')

# ── Universidad de Chile ──
s('src-uchile-001','uchile','Historia · Centro de Estudios en Derecho, Tecnología y Sociedad (CE3)','Facultad de Derecho, Universidad de Chile','pagina-institucional','https://derecho.uchile.cl/centro-estudios-derecho-tecnologia-sociedad/quienes-somos/historia',ND,ND,'vigente','FUENTE_ABIERTA','intento-2a','Genealogía CCIJ → CIJ → CEDI → CE3, 1988–2025. Estructura de derecho y tecnología; la especificidad en IA se evalúa aparte.')
s('src-uchile-002','uchile','Diploma en Derecho e Inteligencia Artificial · edición 2022','Postgrados Derecho, Universidad de Chile','programa-postgrado','https://postgrados.derecho.uchile.cl/diploma-en-derecho-e-inteligencia-artificial','2022','anio','historico','FUENTE_ABIERTA','intento-2a','No es duplicado de src-uchile-003: la URL difiere en una partícula y corresponde a la edición 2022. Juntas prueban continuidad.')
s('src-uchile-003','uchile','Diploma en Derecho e Inteligencia Artificial · segundo semestre de 2026','Postgrados Derecho, Universidad de Chile','programa-postgrado','https://postgrados.derecho.uchile.cl/diploma-derecho-e-inteligencia-artificial','2026-08-01','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-2b; intento-3a','Sustituye la dependencia en las versiones 2022 y 2023 como única prueba de continuidad.')
s('src-uchile-004','uchile','¿De quién es la responsabilidad civil cuando falla la IA?','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/noticias/225314/de-quien-es-la-responsabilidad-civil-cuando-falla-la-ia',ND,ND,'vigente','FUENTE_ABIERTA','intento-2a','Proyecto de internacionalización adjudicado al Departamento de Derecho Privado; monto no localizado.')
s('src-uchile-005','uchile','Tesis en Inteligencia Artificial · repositorio CE3','Facultad de Derecho, Universidad de Chile','repositorio','https://derecho.uchile.cl/centro-estudios-derecho-tecnologia-sociedad/publicaciones/tesis/tesis-en-inteligencia-artificial',ND,ND,'vigente','FUENTE_ABIERTA','intento-2a','Lista tesis sobre IA judicial, propiedad intelectual y transparencia algorítmica entre 2008 y 2025.')
s('src-uchile-006','uchile','Publicaciones · Tesis del CE3','Facultad de Derecho, Universidad de Chile','repositorio','https://derecho.uchile.cl/centro-estudios-derecho-tecnologia-sociedad/publicaciones/tesis',ND,ND,'vigente','FUENTE_ABIERTA','intento-3a','Índice general del repositorio; posee categoría específica de IA.')
s('src-uchile-007','uchile','CE3 consolida liderazgo en el país y en Latinoamérica','Facultad de Derecho, Universidad de Chile','resultado-institucional','https://derecho.uchile.cl/noticias/236453/ce3-consolida-liderazgo-en-el-pais-y-en-latinoamerica','2026-01-08','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-3a','Publicada el 08-01-2026 y probatoria de actividad de 2025: publication_date y fact_period no coinciden. Los juicios de «liderazgo» son autoevaluación institucional.')
s('src-uchile-008','uchile','Congreso internacional aborda desafíos de la IA en el derecho privado','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/noticias/228982/congreso-internacional-aborda-desafios-de-la-ia-en-el-derecho-privado',ND,ND,'vigente','PROPUESTO','intento-2a; intento-3a','CONFLICTO DE FECHA: intento-2a la data el 09-06-2025 y intento-3a el 27-05-2025. Se deja sin fecha hasta abrir el original.')
s('src-uchile-009','uchile','Workshop IA y Derecho Privado: casos prácticos','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/agenda/231464/workshop-ia-y-derecho-privado-casos-practicos','2025-08-29','dia','vigente','FUENTE_ABIERTA','intento-2a','Corrobora continuidad del proyecto de responsabilidad civil e IA.')
s('src-uchile-010','uchile','Consideraciones para una excepción de derechos de autor en la formación de sistemas de IA','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/agenda/241228/consideraciones-para-una-excepcion-de-derechos-de-autor-en-la','2026-06-16','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Actividad de extensión e investigación; por sí sola no eleva institucionalización.')
s('src-uchile-011','uchile','Profesor Alberto Cerda asume como director del CE3','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/noticias/224204/profesor-alberto-cerda-asume-como-director-del-ce3','2025-01-03','dia','vigente','FUENTE_ABIERTA','intento-3a','Nombramiento confirmado por el Consejo de Facultad.')
s('src-uchile-012','uchile','Seminario Inteligencia Artificial y acceso a la justicia','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/agenda/227755/seminario-inteligencia-artificial--acceso-a-la-justicia','2025-05-14','dia','vigente','FUENTE_ABIERTA','intento-3a','Actividad de dos jornadas, 14 y 15 de mayo de 2025.')
s('src-uchile-013','uchile','CE3 convoca a Programa de Visitas Académicas de América Latina y el Caribe','Facultad de Derecho, Universidad de Chile','noticia-institucional','https://derecho.uchile.cl/noticias/238418/ce3-convoca-a-programa-de-visitas-academicas-de-america-latina-y-el-caribe','2026-04-02','dia','vigente','FUENTE_ABIERTA','intento-3b','Estadías de cuatro a seis semanas con colaboración en proyectos, publicaciones y cursos.')
s('src-uchile-014','uchile','Diploma en Derecho e Inteligencia Artificial para la Contraloría General de la República','Siembra Abierta, Universidad de Chile','pagina-institucional','https://siembraabierta.uchile.cl/initiatives/161445',ND,ND,'vigente','PROPUESTO','intento-3a','Iniciativa ejecutada entre julio y noviembre de 2025, alcance nacional. El documento fuente declara timeout al abrir el original.')
s('src-uchile-015','uchile','Lineamientos para el uso de IA en trabajos de titulación','Universidad de Chile','politica','https://uchile.cl/informacion-y-bibliotecas/lineamientos-uso-ia-en-tesis','2026','anio','vigente','FUENTE_ABIERTA','intento-3a','Política universitaria aplicable a Derecho, no dictada por la Facultad de Derecho.')
s('src-uchile-016','uchile','Curso institucional sobre IA generativa en línea','Vicerrectoría de Tecnologías de la Información, Universidad de Chile','pagina-institucional','https://vti.uchile.cl/curso-sobre-ia-online','2025-09-09','dia','vigente','FUENTE_ABIERTA','intento-3a','Capacitación de 27 horas dirigida a toda la comunidad universitaria. Atribución a la universidad, no a Derecho.')

# ── Universidad Diego Portales ──
s('src-udp-001','udp','Académico Rafael Mery es nombrado director de Inteligencia Artificial y Derecho UDP','Facultad de Derecho UDP','noticia-institucional','https://derecho.udp.cl/academico-rafael-mery-es-nombrado-director-de-inteligencia-artificial-y-derecho-udp','2025-09-12','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','El nombramiento y la creación de la Dirección están documentados; los cambios de malla que anuncia, no. El registro se parte en dos en vez de promediarse.')
s('src-udp-002','udp','Dirección de Inteligencia Artificial y Derecho','Facultad de Derecho UDP','pagina-institucional','https://derecho.udp.cl/direccion-de-inteligencia-artificial-y-derecho',ND,ND,'vigente','FUENTE_ABIERTA','intento-3b','Anuncia trabajo desde el primer semestre, un taller de IA en escritura legal y formación posterior. Anuncio, no ejecución acreditada (L-3).')
s('src-udp-003','udp','Nuevo convenio entre UDP y sector tecnológico busca potenciar desarrollos en inteligencia artificial y derecho','Vicerrectoría de Investigación e Innovación UDP','noticia-institucional','https://investigacioneinnovacion.udp.cl/nuevo-convenio-entre-udp-y-sector-tecnologico-busca-potenciar-desarrollos-en-inteligencia-artificial-y-derecho','2026-04-07','dia','vigente','FUENTE_ABIERTA','intento-2b','Convenio I+D+i con Quantico y Merlín Research, suscrito por la Vicerrectoría con participación de Derecho.')

# ── Universidad de los Andes ──
s('src-uandes-001','uandes','Investigación aplicará IA para mejorar la certeza jurídica en la evaluación ambiental de proyectos en Chile','Universidad de los Andes','noticia-institucional','https://uandes.cl/actualidad/noticias/investigacion-aplicara-ia-para-mejorar-la-certeza-juridica-en-la-evaluacion-ambiental-de-proyectos-en-chile','2025-09-22','dia','vigente','FUENTE_ABIERTA','intento-2b','Proyecto FONDEF en curso. Consta por noticia universitaria; falta verificación en ANID (L-8).')
s('src-uandes-002','uandes','Investigación aplicará IA para agilizar la evaluación ambiental de proyectos en Chile','Investiga UANDES','noticia-institucional','https://investiga.uandes.cl/es/investigacion-aplicara-ia-para-agilizar-la-evaluacion-ambiental-de-proyectos-en-chile','2025-11-05','dia','vigente','FUENTE_ABIERTA','intento-3b','Describe equipo interfacultades e interuniversitario, con participación de la PUCV. Misma iniciativa que src-uandes-001: no se cuenta dos veces.')
s('src-uandes-003','uandes','IA al servicio de la edificación: prototipo del CET e Ingeniería fue finalista en concurso del Gobierno y el BID','Universidad de los Andes','noticia-institucional','https://uandes.cl/actualidad/noticias/ia-al-servicio-de-la-edificacion-prototipo-del-cet-e-ingenieria-fue-finalista-en-concurso-del-gobierno-y-el-bid','2025-10-27','dia','vigente','FUENTE_ABIERTA','intento-2b','DOMus AI lo desarrollan el CET e Ingeniería: la unidad principal no es Derecho. Se atribuye a la universidad.')
s('src-uandes-004','uandes','Curso en Compliance, ética pública y nuevas tecnologías','Postgrados UANDES','programa-postgrado','https://postgrados.uandes.cl/cursos/curso-en-compliance-etica-publica-y-nuevas-tecnologias',ND,ND,'vigente','FUENTE_ABIERTA','intento-3b','Curso de la Facultad de Derecho iniciado el 05-08-2026; incluye legalidad y control en la implementación de IA por la Administración.')
s('src-uandes-005','uandes','Seminario: el uso de obras ajenas por los sistemas de inteligencia artificial generativa','Postgrados UANDES','noticia-institucional','https://postgrados.uandes.cl/seminarios/seminario-el-uso-de-obras-ajenas-por-los-sistemas-de-inteligencia-artificial-generativa-hacia-una-nueva-excepcion-de-los-derechos-de-autor','2026-05-14','dia','vigente','FUENTE_ABIERTA','intento-3b','Actividad de la Facultad de Derecho sobre excepción de minería de datos.')

# ── Universidad Adolfo Ibáñez ──
s('src-uai-001','uai','Laboratorio de Justicia Centrada en las Personas UAI dicta curso de IA para la Academia Judicial','Facultad de Derecho UAI','noticia-institucional','https://uai.cl/noticias/derecho/laboratorio-de-justicia-centrada-en-las-personas-uai-dicta-curso-de-ia-para-la-academia-judicial','2026-04-22','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Nueva versión de una formación aplicada: la fuente prueba recurrencia, no cobertura ni resultados.')
s('src-uai-002','uai','Facultad de Derecho firma convenio con Legu, legaltech que impulsa el acceso al derecho mediante IA','Universidad Adolfo Ibáñez','noticia-institucional','https://alumni.uai.cl/news/noticias-uai/905/905-Facultad-de-Derecho-firma-convenio-con-Legu-legaltech-que-impulsa-el-acceso-al-derecho-mediante-IA','2026-01-12','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Convenio firmado el 06-01-2026. No hay evidencia pública de cobertura estudiantil, productos ni resultados: existir no es funcionar (L-3).')
s('src-uai-003','uai','Ricardo Lillo, Esteban Pereira y Javier Wilenmann se adjudican proyectos Fondecyt Regular 2026','Universidad Adolfo Ibáñez','noticia-institucional','https://uai.cl/noticias/derecho/ricardo-lillo-esteban-pereira-y-javier-wilenmann-se-adjudican-proyectos-fondecyt-regular-2026','2026-01-29','dia','vigente','FUENTE_ABIERTA','intento-3b','Fondecyt Regular sobre debido proceso en la era de la IA. Consta por noticia universitaria; falta verificación en ANID (L-8).')

# ── Universidad Andrés Bello ──
s('src-unab-001','unab','Facultad de Derecho UNAB presentó su cuenta pública 2025','Universidad Andrés Bello','resultado-institucional','https://noticias.unab.cl/facultad-de-derecho-unab-presento-su-cuenta-publica-2025-con-foco-en-innovacion-internacionalizacion-y-fortalecimiento-academico','2026-03-01','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Informa asistentes de IA generativa integrados en Canvas en asignaturas nombradas de primer ciclo. Es la institución describiéndose a sí misma.')
s('src-unab-002','unab','UNAB lanzó Asesor Virtual de Insolvencia','Universidad Andrés Bello','noticia-institucional','https://noticias.unab.cl/unab-lanzo-asesor-virtual-de-insolvencia','2025-10-27','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Lanzamiento el 23-10-2025 con la Superintendencia de Insolvencia y Reemprendimiento.')
s('src-unab-003','unab','UNAB impulsa MIAsistentes, un ecosistema de inteligencia artificial para acompañar el aprendizaje','Universidad Andrés Bello','noticia-institucional','https://noticias.unab.cl/unab-impulsa-miasistentes-un-ecosistema-de-inteligencia-artificial-para-acompanar-el-aprendizaje-y-la-experiencia-universitaria','2026-08-31','dia','vigente','FUENTE_ABIERTA','intento-3b','Capacidad de toda la universidad. No se atribuye a Derecho sin datos de aplicación específica.')
s('src-unab-004','unab','Diplomado en Derecho, Innovación y Tecnología','Postgrado UNAB','programa-postgrado','https://postgrado.unab.cl/programas/diplomado-en-derecho-innovacion-y-tecnologia',ND,ND,'vigente','PROPUESTO','intento-2b','RECUPERADA EN LA RONDA 3: citada en la tabla-resumen de intento-2b sin registro propio, quedó fuera del inventario de 72. Falta comprobar si la IA es componente sustantivo o si el programa es ADYACENTE.')

# ── Universidad del Desarrollo ──
s('src-udd-001','udd','Carrera de Derecho · malla y admisión','Facultad de Derecho UDD','curricular','https://derecho.udd.cl/carrera/derecho',ND,ND,'vigente','FUENTE_ABIERTA','intento-2b; intento-3b','La malla declara «LegalTech + IA» con talleres propios, pero la página está orientada a Admisión 2027: prueba diseño curricular anunciado, no curso dictado (L-3).')
s('src-udd-002','udd','Estudiantes de debate y litigación UDD entrenan con inteligencia artificial en RealitecUDD','Facultad de Derecho UDD','noticia-institucional','https://derecho.udd.cl/noticias/2025/04/estudiantes-de-debate-y-litigacion-udd-entrenan-con-inteligencia-artificial-en-realitecudd','2025-04-09','dia','vigente','FUENTE_ABIERTA','intento-2b','Entrenamiento práctico con IA y realidad virtual. La realidad virtual no es IA: sólo el componente de IA cuenta.')
s('src-udd-003','udd','Workshop del Doctorado aborda los desafíos regulatorios de la IA','Facultad de Derecho UDD','noticia-institucional','https://derecho.udd.cl/noticias/2026/01/workshop-del-doctorado-aborda-los-desafios-regulatorios-de-la-ia-y-el-rol-del-derecho-ante-los-avances-tecnologicos','2026-01-14','dia','vigente','FUENTE_ABIERTA','intento-3b','Actividad de formación doctoral sobre regulación de IA.')
s('src-udd-004','udd','Estudiantes de Derecho UDD Concepción destacan en el cierre de una nueva edición de Incuba UDD','Facultad de Derecho UDD','noticia-institucional','https://derecho.udd.cl/noticias/2026/06/estudiantes-de-derecho-udd-concepcion-destacan-en-el-cierre-de-una-nueva-edicion-de-incuba-udd','2026-06-30','dia','vigente','FUENTE_ABIERTA','intento-3b','Proyecto estudiantil Hereda Fácil. Atribución estudiantil, no de la Facultad.')

# ── Universidad Autónoma de Chile ──
s('src-uautonoma-001','uautonoma','Alfabetización en IA generativa en Derecho alcanza al 80 % de docentes y se amplía a estudiantes','Universidad Autónoma de Chile','noticia-institucional','https://uautonoma.cl/noticias/alfabetizacion-en-ia-generativa-en-derecho-alcanza-al-80-de-docentes-y-se-amplia-a-estudiantes','2026-05-27','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Derriba el cero heredado de uso interno. Acredita capacitación, no adopción: cuántos docentes implementaron después actividades en sus cursos queda pendiente.')
s('src-uautonoma-002','uautonoma','Facultad de Derecho pone en marcha programa de formación en inteligencia artificial para estudiantes de sus clínicas jurídicas','Universidad Autónoma de Chile','noticia-institucional','https://uautonoma.cl/noticias/facultad-de-derecho-pone-en-marcha-innovador-programa-de-formacion-en-inteligencia-artificial-para-estudiantes-de-sus-clinicas-juridicas','2026-08-10','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Programa de 18 semanas en las tres sedes. Programado y en marcha al corte; sin resultados publicados.')
s('src-uautonoma-003','uautonoma','Estudiantes de Derecho egresan del Minor en Inteligencia Artificial y Derecho','Universidad Autónoma de Chile','noticia-institucional','https://uautonoma.cl/noticias/estudiantes-de-derecho-egresan-del-minor-en-inteligencia-artificial-y-derecho','2026-01-09','dia','vigente','FUENTE_ABIERTA','intento-3b','Ceremonia de enero de 2026 correspondiente al año académico 2025: publication_date y fact_period no coinciden.')

# ── Universidad Central ──
s('src-ucentral-001','ucentral','U. Central destaca en el Latin America Innovation Showcase del QS Reimagine Education Conference 2025','Universidad Central de Chile','noticia-institucional','https://noticias.ucentral.cl/noticias/u-central-destaca-en-el-latin-america-innovation-showcase-del-qs-reimagine-education-conference-2025-con-innovadora-practica-docente','2025-12-03','dia','vigente','FUENTE_ABIERTA','intento-2b','Docente iLex, asistente generativo desarrollado por Derecho para retroalimentación y rúbricas.')
s('src-ucentral-002','ucentral','Inteligencia artificial y derechos fundamentales · Revista DIE','Universidad Central de Chile','noticia-institucional','https://noticias.ucentral.cl/noticias/inteligencia-artificial-derechos-fundamentales-revista-die','2026-08-25','dia','vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Número de la revista del Doctorado dedicado a Derecho e IA.')
s('src-ucentral-003','ucentral','Programa de IA & LegalTech · FACDEH','Facultad de Ciencias Jurídicas y Sociales, Universidad Central','pagina-institucional','https://facdeh.ucentral.cl/legal-tech',ND,ND,'vigente','FUENTE_ABIERTA','intento-3b','La unidad vigente es Programa IA & LegalTech; sustituye la denominación «Cátedra LegalTech» del antecedente, que se conserva como antecedente.')
s('src-ucentral-004','ucentral','Universidad Central presenta IDEA UCEN, nueva plataforma de búsqueda','Universidad Central de Chile','noticia-institucional','https://noticias.ucentral.cl/noticias/universidad-central-presenta-idea-ucen-nueva-plataforma-de-busqueda',ND,ND,'vigente','PROPUESTO','intento-2b','RECUPERADA EN LA RONDA 3: citada en la tabla-resumen de intento-2b sin registro propio, quedó fuera del inventario de 72. Infraestructura de la universidad; falta comprobar vigencia en 2026 (L-10).')

# ── Pontificia Universidad Católica de Valparaíso ──
s('src-pucv-001','pucv','Legal Management Innovation Lab: nuevo laboratorio de innovación','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho/noticias/legal-management-innovation-lab-nuevo-laboratorio-de-innovacion','2022-01-06','dia','vigente','FUENTE_ABIERTA','intento-2a','LMIL nace como laboratorio de transformación digital e innovación legal: ADYACENTE, no IA específica.')
s('src-pucv-002','pucv','Núcleo de Derecho, Inteligencia Artificial y Tecnología PUCV','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho/noticias/nucleo-de-derecho-inteligencia-artificial-y-tecnologia-pucv-desarrolla','2023-11-20','dia','vigente','FUENTE_ABIERTA','intento-2a','Afirma que el Núcleo se oficializó en 2020. En 2026 la unidad es Programa DIAT, no «Centro DIAT».')
s('src-pucv-003','pucv','Tecnología jurídica en acción: el Programa DIAT PUCV integra la inteligencia artificial','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/tecnologia-juridica-en-accion-programa-diat-pucv-integra-la','2024-04-24','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-3a','Prompts Socráticos y chatbot en Filosofía del Derecho: IA aplicada dentro de una asignatura jurídica.')
s('src-pucv-004','pucv','ScribeClaroPUCV, herramienta para una redacción jurídica clara','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/scribeclaropucv-innovadora-herramienta-para-una-redaccion-juridica-clara','2025-01-30','dia','vigente','FUENTE_ABIERTA','intento-2a','Herramienta creada inicialmente para estudiantes de Derecho, con apoyo del Programa de Desarrollo Docente.')
s('src-pucv-005','pucv','Destacada participación de estudiantes en la jornada de cierre del Taller de IA y Prompting Jurídico','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/destacada-participacion-de-estudiantes-en-la-jornada-de-cierre-del','2025-10-07','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-3a; intento-3b','Edición 2025: tres jornadas y cerca de 90 participantes. Cuántos asistieron no dice si algo cambió.')
s('src-pucv-006','pucv','Facultad y Escuela de Derecho PUCV se adjudican dos proyectos de Vinculación con el Medio','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/facultad-y-escuela-de-derecho-pucv-se-adjudican-dos-proyectos-de','2026-06-03','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-2b; intento-3a; intento-3b','Adjudicación competitiva interna. Financiamiento concursable, no basal.')
s('src-pucv-007','pucv','Universidad presentó decálogo para el uso ético de la inteligencia artificial','Pontificia Universidad Católica de Valparaíso','noticia-institucional','https://pucv.cl/pucv/noticias/destacadas/universidad-presento-decalogo-para-el-uso-etico-de-la-inteligencia','2026-01-09','dia','vigente','FUENTE_ABIERTA','intento-2a; intento-2b; intento-3a; intento-3b','Lineamiento universitario liderado desde la Unidad de Integridad Académica, con liderazgo de una profesora de Derecho. No es política propia de la Escuela de Derecho.')
s('src-pucv-008','pucv','Profesor James M. Cooper encabezó workshop internacional sobre manejo de IA en el ámbito legal','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/profesor-james-m-cooper-encabezo-workshop-internacional-sobre-manejo-de','2026-06-18','dia','vigente','FUENTE_ABIERTA','intento-2b','Workshop para alumni sobre manejo, gobernanza e implementación responsable de IA.')
s('src-pucv-009','pucv','Diplomado Legal Management Program y Legal Management Innovation Lab','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho/noticias/diplomado-legal-management-program-y-legal-management-innovation-lab','2023-04-18','dia','vigente','FUENTE_ABIERTA','intento-2a','FDI financiado por Mineduc para un componente ADYACENTE, no para IA específica.')
s('src-pucv-010','pucv','Laboratorio de Innovación Legal y Programa de Derecho e Inteligencia Artificial se adjudican fondos','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/laboratorio-de-innovacion-legal-y-programa-de-derecho-e-inteligencia','2025-08-11','dia','vigente','FUENTE_ABIERTA','intento-3a','Adjudicación 2025. Junto con src-pucv-006 documenta financiamiento competitivo en dos años consecutivos.')
s('src-pucv-011','pucv','IV versión de Innova Day 2025','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derecho-pucv/noticias/exitosa-iv-version-de-innova-day-2025-fomentando-la-innovacion-legal',ND,ND,'vigente','FUENTE_ABIERTA','intento-3a','La actividad general es ADYACENTE; sólo el panel sobre automatización e IA genera evidencia específica. No reclasificar todo Innova Day como iniciativa de IA.')
s('src-pucv-012','pucv','Derecho · pregrado PUCV','Pontificia Universidad Católica de Valparaíso','curricular','https://pucv.cl/pucv/pregrado/derecho',ND,ND,'vigente','FUENTE_ABIERTA','intento-3a','El perfil declara competencia en TIC y enlaza al plan de estudios; la revisión pública no permitió verificar una línea curricular obligatoria en IA. No autoriza a afirmar que no exista (L-7).')
s('src-pucv-013','pucv','Universidad habilita la herramienta Gemini IA para fortalecer el trabajo académico','Pontificia Universidad Católica de Valparaíso','noticia-institucional','https://pucv.cl/pucv/noticias/vida-universitaria/universidad-habilita-herramienta-gemini-ia-para-fortalecer-el-trabajo','2026-03-19','dia','vigente','FUENTE_ABIERTA','intento-3b','Demuestra acceso institucional desde marzo de 2026, no adopción efectiva en Derecho. Infraestructura, participación y uso son tres cosas distintas.')
s('src-pucv-014','pucv','Profesor Eduardo Aldunate publica artículo en revista indexada','Facultad de Derecho PUCV','noticia-institucional','https://pucv.cl/uuaa/derechopublico/noticias/profesor-eduardo-aldunate-publica-articulo-en-prestigiosa-revista',ND,ND,'vigente','PROPUESTO','intento-3a','Aparece en la lista de fuentes de la narrativa PUCV de intento-3a. No acredita actividad de IA: se conserva como contexto y no alimenta ninguna evidencia.')

# ── Universidad de Concepción ──
s('src-udec-001','udec','Facultad de Ciencias Jurídicas y Sociales UdeC realizó seminario sobre inteligencia artificial','Facultad de Ciencias Jurídicas y Sociales UdeC','noticia-institucional','https://jur.udec.cl/content/facultad-de-ciencias-jur%C3%ADdicas-y-sociales-udec-realiz%C3%B3-seminario-sobre-inteligencia',ND,ND,'vigente','FUENTE_ABIERTA','intento-2b; intento-3b','Actividad del 21-04-2026: demostraciones de modelos de lenguaje para lectura, investigación y redacción jurídica.')
s('src-udec-002','udec','Seminario «Derecho en la Smart Era»','Facultad de Ciencias Jurídicas y Sociales UdeC','noticia-institucional','https://juridicasysociales.udec.cl/content/seminario-%E2%80%9Cderecho-en-la-smart-era%E2%80%9D-reuni%C3%B3-destacados-expositores-y-una-gran-audiencia-en-la','2025-10-02','dia','inaccesible','FUENTE_ABIERTA','intento-2b','El certificado del servidor no cubre el nombre de host: el navegador mostrará una advertencia de seguridad. El contenido existe. Antes de publicar conviene buscar el mismo hecho en jur.udec.cl.')
s('src-udec-003','udec','Facultad realizó taller de inteligencia artificial para académicos y académicas','Facultad de Ciencias Jurídicas y Sociales UdeC','noticia-institucional','https://jur.udec.cl/content/facultad-realiz%C3%B3-taller-de-inteligencia-artificial-para-acad%C3%A9micos-y-acad%C3%A9micas',ND,ND,'vigente','FUENTE_ABIERTA','intento-3b','Taller presencial sobre uso crítico y pedagógico de IA generativa. La fuente no declara fecha de publicación.')
s('src-udec-004','udec','[genIA] · programa interdisciplinario UdeC','Universidad de Concepción','pagina-institucional','https://genia.udec.cl','2026-02-10','dia','vigente','FUENTE_ABIERTA','intento-3b','Capacidad de toda la universidad, no estructura de Derecho. Reclasificada como ADYACENTE para la Facultad.')

hdr=['source_id','university_id','title','publisher','source_type','url','archived_url','published_date','date_precision','accessed_date','document_status','confidence','workflow_status','created_by','verified_by','notes']
out='content/reports/01_ia_escuelas_derecho_chile/canonical/dataset/fuentes.csv'
with open(out,'w',newline='',encoding='utf-8') as f:
    w=csv.DictWriter(f,fieldnames=hdr); w.writeheader()
    for r in R: w.writerow(r)
ids=[r['source_id'] for r in R]
assert len(ids)==len(set(ids)), 'IDs duplicados'
urls=[r['url'] for r in R]
assert len(urls)==len(set(urls)), 'URLs duplicadas'
print('filas:',len(R))
from collections import Counter
print(Counter(r['university_id'] or 'nacional' for r in R))
