import type { Publication } from '@/types';

/**
 * Catálogo de publicaciones.
 *
 * Origen: ficha de autor en Dialnet, contrastada artículo por artículo contra
 * la publicación original cuando estaba accesible. Cada entrada conserva el
 * título **literal** del índice, con sus erratas incluidas: normalizar la
 * ortografía de un título rompe la búsqueda exacta, que es justamente para lo
 * que sirve un catálogo.
 *
 * Lo que este archivo deliberadamente NO contiene:
 *
 * - `thesis`. Sin acceso al texto completo, resumir el argumento central de un
 *   artículo a partir de su título es inventar despacio. El campo existe en el
 *   tipo y queda vacío hasta que alguien lea la obra.
 * - Indicadores bibliométricos. El informe de origen traía un h-index y un
 *   recuento de citas atribuidos a una plataforma no accesible; no se
 *   incorporan. Ver `docs/AUDITORIA-PERFIL-ALDUNATE.md`.
 *
 * `concepts` se deriva del título y de la sede de publicación, no de una
 * lectura interpretativa: es un índice temático, no una atribución de posición.
 */
export const publications: Publication[] = [
  /* ── Libros ── */
  {
    id: 'libro-derechos-fundamentales',
    title: 'Derechos fundamentales',
    kind: 'libro',
    year: 2008,
    venue: 'LegalPublishing, Santiago',
    concepts: ['derechos-fundamentales', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor', 'derechopedia'],
  },
  {
    id: 'libro-jurisprudencia-constitucional',
    title: 'Jurisprudencia constitucional 2006-2008',
    kind: 'libro',
    year: 2009,
    venue: 'LegalPublishing, Santiago',
    concepts: ['justicia-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['derechopedia'],
  },

  /* ── Artículos, del más reciente al más antiguo ── */
  {
    id: 'art-2024-asistentes-virtuales',
    title: 'La enseñanza-aprendizaje del derecho a través de asistentes virtuales',
    kind: 'articulo',
    year: 2024,
    venue: 'Revista de Pedagogía Universitaria y Didáctica del Derecho 11(1), pp. 31–48',
    coauthors: [
      'Antonio Faúndez Ugalde',
      'Rafael Mellado Silva',
      'Johann Benfeld',
    ],
    concepts: ['ia-derecho', 'ensenanza'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2021-acuerdos-chile',
    title: 'Los acuerdos pre y posmatrimoniales en el ordenamiento jurídico chileno',
    kind: 'articulo',
    year: 2021,
    venue: 'Revista de Derecho Privado n.º 40',
    coauthors: ['Carolina Riveros Ferrada'],
    concepts: ['familia'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2016-igualdad',
    title: 'Desglosando la igualdad constitucional',
    kind: 'articulo',
    year: 2016,
    venue: 'Anuario de Derecho Público n.º 1, pp. 209–245',
    concepts: ['igualdad', 'derechos-fundamentales'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2016-acuerdos-modelos',
    title: 'Acuerdos pre y posmatrimoniales: Conceptos y modelos de regulación',
    kind: 'articulo',
    year: 2016,
    venue: 'Revista de Derecho 29(2), pp. 131–155',
    coauthors: ['Carolina Riveros Ferrada'],
    concepts: ['familia'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2014-derechos-sociales',
    title: 'De los derechos sociales de prestación al gobierno aristocrático',
    kind: 'articulo',
    year: 2014,
    venue: 'Anuario de Derecho Público n.º 1, pp. 21–42',
    concepts: ['derechos-sociales', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2012-potestad-sancionadora',
    title: 'Las bases constitucionales de la potestad sancionadora de la Administración',
    kind: 'articulo',
    year: 2012,
    venue:
      'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 39(2), pp. 337–361',
    coauthors: ['Eduardo Cordero Quinzacara'],
    concepts: ['potestad-sancionadora', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2010-neoconstitucionalismo-anuario',
    title: 'Neoconstitucionalismo',
    kind: 'articulo',
    year: 2010,
    venue: 'Anuario de Derecho Público n.º 1, pp. 361–369',
    concepts: ['neoconstitucionalismo', 'teoria-constitucional'],
    relatedWorks: ['art-2010-neoconstitucionalismo-critica'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2010-tratados',
    title:
      'La posición de los tratados internacionales en el sistema de fuentes del ordenamiento jurídico chileno',
    kind: 'articulo',
    year: 2010,
    venue: 'Ius et Praxis 16(2), pp. 185–210',
    concepts: ['fuentes'],
    relatedWorks: ['art-2009-fuerza-normativa'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2010-neoconstitucionalismo-critica',
    title: 'Aproximación conceptual y crítica al neoconstitucionalismo',
    kind: 'articulo',
    year: 2010,
    venue: 'Revista de Derecho (Valdivia) 23(1), pp. 79–102',
    concepts: ['neoconstitucionalismo', 'fuentes', 'teoria-constitucional'],
    relatedWorks: ['art-2009-fuerza-normativa', 'art-2010-neoconstitucionalismo-anuario'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2009-fuerza-normativa',
    title: 'La fuerza normativa de la Constitución y el sistema de fuentes del Derecho',
    kind: 'articulo',
    year: 2009,
    venue:
      'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 32(1), pp. 443–484',
    question:
      'Qué significan hoy, en la doctrina y la jurisprudencia nacionales, las invocaciones a la fuerza normativa de la Constitución, y qué efecto tiene ese principio sobre el sistema de fuentes.',
    abstract:
      'Según el resumen de la propia publicación, el trabajo revisa los sentidos corrientes del principio de fuerza normativa de la Constitución, su origen y su significado en el derecho constitucional, y examina críticamente su efecto sobre el sistema de fuentes.',
    concepts: ['fuentes', 'teoria-constitucional', 'neoconstitucionalismo'],
    relatedWorks: ['art-2010-neoconstitucionalismo-critica', 'art-2010-tratados'],
    url: 'https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-68512009000100013',
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor', 'scielo-fuerza-normativa', 'projure-pucv'],
  },
  {
    id: 'art-2009-potestades-normativas',
    title: "La distribución de potestades normativas en la 'Constitución'",
    kind: 'articulo',
    year: 2009,
    venue:
      'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 33(2), pp. 371–390',
    concepts: ['fuentes', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2008-propiedad-historia',
    title: 'Evolución histórica del concepto de propiedad',
    kind: 'articulo',
    year: 2008,
    venue: 'Revista de Estudios Histórico-Jurídicos n.º 30, pp. 345–385',
    coauthors: ['Eduardo Cordero Quinzacara'],
    concepts: ['propiedad'],
    relatedWorks: ['art-2006-expropiacion', 'art-1997-propiedad-garantias'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2007-amparo-habeas-corpus',
    title: 'Panorama actual del amparo y hábeas corpus en Chile',
    kind: 'articulo',
    year: 2007,
    venue: 'Estudios Constitucionales, año 5, n.º 1, pp. 19–29',
    concepts: ['derechos-fundamentales', 'justicia-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2007-sentencia-amparo',
    title: 'Sentencia sobre amparo de derechos fundamentales (Tribunal Constitucional)',
    kind: 'articulo',
    year: 2007,
    venue: 'Revista de Derecho 20(2), pp. 221–238',
    concepts: ['justicia-constitucional', 'derechos-fundamentales'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2007-reforma-2005',
    title:
      'La reforma constitucional del año 2005 desde la teoría del derecho y la teoría de la Constitución',
    kind: 'articulo',
    year: 2007,
    venue: 'Revista de Derecho Público n.º 69, 1, pp. 35–44',
    concepts: ['teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2006-expropiacion',
    title:
      'Limitación y expropiación: Scilla y Caribdis de la dogmática constitucional de la propiedad',
    kind: 'articulo',
    year: 2006,
    venue: 'Revista Chilena de Derecho 33(2), pp. 285–303',
    question:
      'Con qué criterio se distingue una limitación al dominio de una expropiación, si la jurisprudencia constitucional las trata como nociones de un mismo continuo separadas solo por la intensidad de su efecto patrimonial.',
    abstract:
      'Según el resumen de la propia publicación, el trabajo examina los criterios necesarios para distinguir entre limitación y expropiación, frente a la tesis del Tribunal Constitucional que las sitúa en un continuo conceptual diferenciado únicamente por la entidad del efecto patrimonial.',
    concepts: ['propiedad', 'derechos-fundamentales', 'justicia-constitucional'],
    relatedWorks: ['art-2008-propiedad-historia', 'art-1997-propiedad-garantias'],
    url: 'https://www.scielo.cl/scielo.php?pid=S0718-34372006000200005&script=sci_abstract',
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor', 'scielo-expropiacion'],
  },
  {
    id: 'art-2006-politica-fiscal',
    title: 'Política fiscal y protección social',
    kind: 'articulo',
    year: 2006,
    venue: 'Revista de la CEPAL n.º 90, pp. 87–104',
    coauthors: ['Ricardo Martner'],
    concepts: ['derechos-sociales'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2005-control-preventivo',
    title: 'Problemas del control preventivo de constitucionalidad de las leyes',
    kind: 'articulo',
    year: 2005,
    venue: 'Estudios Constitucionales, año 3, n.º 1, pp. 119–126',
    concepts: ['justicia-constitucional', 'fuentes'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2005-contraloria',
    title: 'La evolucion de la funcion de control de la contraloria general de la republica',
    kind: 'articulo',
    year: 2005,
    venue:
      'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 26(2), pp. 19–30',
    concepts: ['potestad-sancionadora'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2003-habilitacion-ambiental',
    title: 'La habilitación ambiental: consecuencias constitucionales de un concepto extenso',
    kind: 'articulo',
    year: 2003,
    venue: 'Anuario, Facultad de Ciencias Jurídicas, Universidad de Antofagasta n.º 9, pp. 73–78',
    concepts: ['ambiental-recursos', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2003-titularidad',
    title: 'La titularidad de los derechos fundamentales',
    kind: 'articulo',
    year: 2003,
    venue: 'Estudios Constitucionales, año 1, n.º 1, pp. 187–201',
    concepts: ['derechos-fundamentales'],
    relatedWorks: ['libro-derechos-fundamentales'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2002-interpretacion-valores',
    title: 'Interpretación, valores y sistema constitucional',
    kind: 'articulo',
    year: 2002,
    venue: 'Cuadernos de Derecho Público n.º 15, pp. 77–90',
    concepts: ['interpretacion', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2002-reformulacion-reglas',
    title:
      'Reformulación de las regalas o elementos de interperetación para una práctica de la interpretación constitucional',
    kind: 'articulo',
    year: 2002,
    venue: 'Revista de Derecho 3(3), pp. 259–273',
    concepts: ['interpretacion'],
    relatedWorks: ['art-2001-doctrina-interpretacion'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2001-doctrina-interpretacion',
    title: 'La doctrina nacional sobre interpretación constitucional; estado y crítica',
    kind: 'articulo',
    year: 2001,
    venue: 'Anuario, Facultad de Ciencias Jurídicas, Universidad de Antofagasta n.º 7, pp. 59–80',
    concepts: ['interpretacion'],
    relatedWorks: ['art-2002-reformulacion-reglas', 'art-1993-interpretacion-decision'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2001-desconstitucionalizacion',
    title: 'La desconstitucionalizacion de la constitucion',
    kind: 'articulo',
    year: 2001,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 22, pp. 17–36',
    concepts: ['teoria-constitucional', 'fuentes'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-2001-constitucion-monarquica',
    title: 'La constitucion monarquica del poder judicial',
    kind: 'articulo',
    year: 2001,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 22, pp. 193–207',
    concepts: ['poder-judicial', 'teoria-constitucional'],
    relatedWorks: ['art-1995-independencia-judicial'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1999-proteccion-acecho',
    title: 'La proteccion al acecho',
    kind: 'articulo',
    year: 1999,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 20, pp. 225–242',
    concepts: ['derechos-fundamentales', 'justicia-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1998-pesca',
    title:
      'Breve noticia sobre el proyecto de ley que introduce el régimen especial de pesca a la ley general de pesca y acuicultura',
    kind: 'articulo',
    year: 1998,
    venue: 'Anuario, Facultad de Ciencias Jurídicas, Universidad de Antofagasta n.º 4, pp. 81–85',
    concepts: ['ambiental-recursos'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1998-teoria-interpretacion',
    title: 'Consideraciones preliminares para una teoría de la interpretación jurídica',
    kind: 'articulo',
    year: 1998,
    venue: 'Revista Chilena de Derecho 25(1), pp. 27–31',
    concepts: ['interpretacion'],
    relatedWorks: ['art-2001-doctrina-interpretacion'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1998-categorias-argumentacion',
    title: 'Categorias para el analisis de la argumentación jurídica del Tribunal Constitucional',
    kind: 'articulo',
    year: 1998,
    venue: 'Revista Chilena de Derecho 25(1), pp. 115–120',
    concepts: ['argumentacion', 'justicia-constitucional'],
    relatedWorks: ['art-1995-deficiencias-argumentacion'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1997-derecho-publico-fin-siglo',
    title: 'El derecho publico a fines de siglo. algunas preguntas abiertas',
    kind: 'articulo',
    year: 1997,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 18, pp. 57–61',
    concepts: ['teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1997-procesal-constitucional',
    title: 'El derecho procesal constitucional desde la perspectiva de la teoria constitucional',
    kind: 'articulo',
    year: 1997,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 18, pp. 87–99',
    concepts: ['justicia-constitucional', 'teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1997-propiedad-garantias',
    title:
      'El concepto del derecho de propiedad en la jurisprudencia constitucional chilena y la teoria de las garantias de instituto',
    kind: 'articulo',
    year: 1997,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 18, pp. 195–221',
    coauthors: ['Jessica Fuentes Olmos'],
    concepts: ['propiedad', 'justicia-constitucional'],
    relatedWorks: ['art-2006-expropiacion', 'art-2008-propiedad-historia'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1995-independencia-judicial',
    title: 'La independencia judicial aproximación teórica',
    kind: 'articulo',
    year: 1995,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 16, pp. 11–26',
    concepts: ['poder-judicial'],
    relatedWorks: ['art-2001-constitucion-monarquica'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1995-deficiencias-argumentacion',
    title: 'Deficiencias en la argumentación jurídica',
    kind: 'articulo',
    year: 1995,
    venue: 'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 16, pp. 27–44',
    concepts: ['argumentacion'],
    relatedWorks: ['art-1998-categorias-argumentacion'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1993-cosa-juzgada',
    title: 'Jurisdicción constitucional y cosa juzgada constitucional',
    kind: 'articulo',
    year: 1993,
    venue: 'Revista Chilena de Derecho 20(2-3), pp. 355–359',
    concepts: ['justicia-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1993-interpretacion-decision',
    title: 'Interpretación constitucional y decisión política',
    kind: 'articulo',
    year: 1993,
    venue:
      'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 15 (1993–1994), pp. 31–66',
    concepts: ['interpretacion', 'teoria-constitucional'],
    relatedWorks: ['art-2001-doctrina-interpretacion'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
  {
    id: 'art-1993-poder-politico',
    title: 'Poder político: Precisiones y nomenclatura',
    kind: 'articulo',
    year: 1993,
    venue:
      'Revista de Derecho de la Pontificia Universidad Católica de Valparaíso 15 (1993–1994), pp. 67–78',
    concepts: ['teoria-constitucional'],
    status: 'publicado',
    verified: true,
    sourceIds: ['dialnet-autor'],
  },
];

/** Índice por id, para resolver `relatedWorks` sin recorrer el arreglo. */
export const publicationById = new Map(publications.map((p) => [p.id, p]));

/** Años cubiertos por el catálogo. Se calcula: escribirlo a mano lo deja obsoleto. */
export const publicationYears = publications
  .map((p) => p.year)
  .filter((y): y is number => typeof y === 'number');

export const corpusSpan = {
  from: Math.min(...publicationYears),
  to: Math.max(...publicationYears),
};
